config/routes.rb
Rails.application.routes.draw do
  root 'reporte#index'
  get 'reporte/index'

  resources :planta
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plantum.rb
class Plantum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planta_controller.rb
class PlantaController < ApplicationController
  before_action :set_plantum, only: [:show, :edit, :update, :destroy]

  # GET /planta
  # GET /planta.json
  def index
    @planta = Plantum.all
  end

  # GET /planta/1
  # GET /planta/1.json
  def show
  end

  # GET /planta/new
  def new
    @plantum = Plantum.new
  end

  # GET /planta/1/edit
  def edit
  end

  # POST /planta
  # POST /planta.json
  def create
    @plantum = Plantum.new(plantum_params)

    respond_to do |format|
      if @plantum.save
        format.html { redirect_to @plantum, notice: 'Plantum was successfully created.' }
        format.json { render :show, status: :created, location: @plantum }
      else
        format.html { render :new }
        format.json { render json: @plantum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planta/1
  # PATCH/PUT /planta/1.json
  def update
    respond_to do |format|
      if @plantum.update(plantum_params)
        format.html { redirect_to @plantum, notice: 'Plantum was successfully updated.' }
        format.json { render :show, status: :ok, location: @plantum }
      else
        format.html { render :edit }
        format.json { render json: @plantum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planta/1
  # DELETE /planta/1.json
  def destroy
    @plantum.destroy
    respond_to do |format|
      format.html { redirect_to planta_url, notice: 'Plantum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plantum
      @plantum = Plantum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plantum_params
      params.require(:plantum).permit(:familia, :genero, :nombre, :germinaciondias, :altura, :precio)
    end
end

app/controllers/reporte_controller.rb
class ReporteController < ApplicationController
  def index
  @plantas = Plantum.all
  @plantasOrdenadas = @plantas.sort_by(&:precio) 
  @plantasAltura = @plantas.sort_by(&:altura) 
  @plantasGerminacion = @plantas.sort_by(&:germinaciondias)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planta_helper.rb
module PlantaHelper
end

app/helpers/reporte_helper.rb
module ReporteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suculenta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planta/_form.html.erb
<%= form_with(model: plantum, local: true) do |form| %>
  <% if plantum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plantum.errors.count, "error") %> prohibited this plantum from being saved:</h2>

      <ul>
      <% plantum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :familia %>
    <%= form.text_field :familia, id: :plantum_familia %>
  </div>

  <div class="field">
    <%= form.label :genero %>
    <%= form.text_area :genero, id: :plantum_genero %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_area :nombre, id: :plantum_nombre %>
  </div>

  <div class="field">
    <%= form.label :germinaciondias %>
    <%= form.number_field :germinaciondias, id: :plantum_germinaciondias %>
  </div>

  <div class="field">
    <%= form.label :altura %>
    <%= form.number_field :altura, id: :plantum_altura %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio, id: :plantum_precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planta/edit.html.erb
<h1>Editing Plantum</h1>

<%= render 'form', plantum: @plantum %>

<%= link_to 'Show', @plantum %> |
<%= link_to 'Back', planta_path %>

app/views/planta/index.html.erb
<html>
<head>
  
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
  <p id="notice"><%= notice %></p>

 

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <img src="http://static.wixstatic.com/media/1b2d5f_fb611b1ffce8be45bee904726235a382.jpg_512" alt="germinarte" style="width:130px; height:50px;"> 
      <a class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li> <%= link_to 'New Plantum', new_plantum_path %> </li>
      <li> <%= link_to 'reporte', reporte_index_path %> </li>
    
    </ul>
  </div>
</nav>

<br></br>

<table class="table">
  <thead>
    <tr class="success">
      <th>Familia</th>
      <th>Genero</th>
      <th>Nombre</th>
      <th>Germinaciondias</th>
      <th>Altura</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planta.each do |plantum| %>
      <tr class="success">
        <td><%= plantum.familia %></td>
        <td><%= plantum.genero %></td>
        <td><%= plantum.nombre %></td>
        <td><%= plantum.germinaciondias %></td>
        <td><%= plantum.altura %></td>
        <td><%= plantum.precio %></td>
        <td><%= link_to 'Show', plantum %></td>
        <td><%= link_to 'Edit', edit_plantum_path(plantum) %></td>
        <td><%= link_to 'Destroy', plantum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>





</body>
</html>

app/views/planta/new.html.erb
<h1>New Plantum</h1>

<%= render 'form', plantum: @plantum %>

<%= link_to 'Back', planta_path %>

app/views/planta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Familia:</strong>
  <%= @plantum.familia %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @plantum.genero %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @plantum.nombre %>
</p>

<p>
  <strong>Germinaciondias:</strong>
  <%= @plantum.germinaciondias %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @plantum.altura %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @plantum.precio %>
</p>

<%= link_to 'Edit', edit_plantum_path(@plantum) %> |
<%= link_to 'Back', planta_path %>

app/views/reporte/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<br></br>

<div class="container">
   <table class="table">
   
   <thead>
     <tr class="success">
      <th>Familia</th>
      <th>Genero</th>
      <th>Nombre</th>
      <th>Germinaciondias</th>
      <th>Altura</th>
      <th>Precio</th>
     
    </tr>
  </thead>

  <tbody>
    <% @plantasOrdenadas.each do |plantum| %>
        <tr class="success">
        <td><%= plantum.familia %></td>
        <td><%= plantum.genero %></td>
        <td><%= plantum.nombre %></td>
        <td><%= plantum.germinaciondias %></td>
        <td><%= plantum.altura %></td>
        <td><%= plantum.precio %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<% plantabarata = @plantasOrdenadas.first %>
<h3>La planta mas barata es: <%= plantabarata.nombre %></h3>

<% plantacara = @plantasOrdenadas.last %>
<h3>La planta mas cara es: <%= plantacara.nombre %></h3>

   <table class="table">
   
   <thead>
     <tr class="success">
      <th>Familia</th>
      <th>Genero</th>
      <th>Nombre</th>
      <th>Germinaciondias</th>
      <th>Altura</th>
      <th>Precio</th>
     
    </tr>
  </thead>

  <tbody>
    <% @plantasAltura.each do |plantum| %>
        <tr class="success">
        <td><%= plantum.familia %></td>
        <td><%= plantum.genero %></td>
        <td><%= plantum.nombre %></td>
        <td><%= plantum.germinaciondias %></td>
        <td><%= plantum.altura %></td>
        <td><%= plantum.precio %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<% plantalta = @plantasAltura.last %>
<h3>La planta mas alta es: <%= plantalta.altura %> <%= plantalta.nombre %></h3>

<% plantabaja = @plantasAltura.first %>
<h3 color: "white">La planta mas baja es: <%= plantabaja.altura %> <%= plantabaja.nombre %></h3>

<table class="table">
   
   <thead>
     <tr class="success">
      <th>Familia</th>
      <th>Genero</th>
      <th>Nombre</th>
      <th>Germinaciondias</th>
      <th>Altura</th>
      <th>Precio</th>
     
    </tr>
  </thead>

  <tbody>
    <% @plantasGerminacion.each do |plantum| %>
        <tr class="success">
        <td><%= plantum.familia %></td>
        <td><%= plantum.genero %></td>
        <td><%= plantum.nombre %></td>
        <td><%= plantum.germinaciondias %></td>
        <td><%= plantum.altura %></td>
        <td><%= plantum.precio %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<% plantaLenta = @plantasGerminacion.last %>
<h3>La planta que mas tarda en germinar: <%= plantaLenta.germinaciondias %> <%= plantaLenta.nombre %></h3>

<% plantaRapida = @plantasGerminacion.first %>
<h3>La planta que menos tarda en germinar: <%= plantaRapida.germinaciondias %> <%= plantaRapida.nombre %></h3>
      
</div>
<%= link_to 'Back', planta_path %>

</body>
</html>